### ISSUE TITLE
No worky on OSX

### ISSUE THREAD

**Issue by claytondukes** [maxim-saplin/NetCoreStorageSpeedTest#5]
Hey, awesome tool, ty! Just wanted to let you know it doesn't work on OSX 10.15.6 (19G73):

```
./CPDT_Console
zsh: exec format error: ./CPDT_Console
```

(works great on our Linux boxes though!)

**Comment by maxim-saplin** [comment]
Hi. The console app is not intended for macOS. You can try CPDT instead (same core functionality): https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.3/CPDT.app.zip

**Comment by claytondukes** [comment]
Wow, even nicer. Ty!
