### ISSUE TITLE
Archive of linux zip is corrupted 

### ISSUE THREAD

**Issue by eshivam** [maxim-saplin/NetCoreStorageSpeedTest#9]
@maxim-saplin archive of linux file is corrupted

**Comment by maxim-saplin** [comment]
https://github.com/maxim-saplin/NetCoreStorageSpeedTest/releases/download/2.0.2-u/CPDT_Linux.zip - works fine on Ubuntu. Archived files are extracted, executable is started in Terminal.

![image](https://user-images.githubusercontent.com/7947027/133983194-cd8e0454-a4e9-4ae0-8f48-f12db8eb5810.png)
